/*
	Copyright 2022 Loophole Labs

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		   http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

import fs from "fs";
import protobuf from "protobufjs";
import { ModuleDeclaration, Project } from "ts-morph";
import { version } from "../package.json";
import { getRootAndNamespace, getTypes } from "./ast";

const proto = protobuf.parse(fs.readFileSync(0, "utf8")).root.toJSON().nested!;

const { root, namespace } = getRootAndNamespace(proto);
const types = getTypes(root);

const project = new Project();

const sourceFile = project.createSourceFile("generated.ts");
sourceFile.addStatements(
  `// Code generated by protoc-gen-ts-polyglot ${version}. DO NOT EDIT.`
);

const rootNamespace = namespace.reduce(
  (prev, curr) =>
    prev.addModule({
      name: curr,
      isExported: true,
    }),
  sourceFile as unknown as ModuleDeclaration
);

const getTypeScriptTypeFromProtoType = (protoTypeName: string) => {
  switch (protoTypeName) {
    case "double":
    case "float":
    case "int32":
    case "uint32":
    case "sint32":
    case "fixed32":
    case "sfixed32":
      return "number";

    case "int64":
    case "uint64":
    case "sint64":
    case "fixed64":
    case "sfixed64":
      return "bigint";

    case "bool":
      return "boolean";

    case "string":
      return "string";

    case "bytes":
      return "Uint8Array";

    default:
      return protoTypeName; // Is reference of other type
  }
};

types.forEach((type) => {
  const classDeclaration = rootNamespace.addClass({
    name: type.typeName,
    isExported: true,
  });

  classDeclaration.addConstructor({
    parameters: type.fields.map((field) => {
      const typescriptType = getTypeScriptTypeFromProtoType(field.typeName);

      return {
        name: field.fieldName,
        type: typescriptType,
      };
    }),
    statements: type.fields.map(
      (field) => `this._${field.fieldName} = ${field.fieldName}`
    ),
  });

  type.fields.forEach((field) => {
    const typescriptType = getTypeScriptTypeFromProtoType(field.typeName);

    classDeclaration.addProperty({
      name: `private _${field.fieldName}`,
      type: typescriptType,
    });

    classDeclaration.addGetAccessor({
      name: field.fieldName,
      returnType: typescriptType,
      statements: `return this._${field.fieldName}`,
    });

    classDeclaration.addSetAccessor({
      name: field.fieldName,
      parameters: [
        {
          name: field.fieldName,
          type: typescriptType,
        },
      ],
      statements: `this._${field.fieldName} = ${field.fieldName}`,
    });
  });
});

process.stdout.write(sourceFile.getFullText());
