name: npm CI

on: [push, pull_request]

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
      - name: Cache the dependency directories
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: npm
      - name: Install dependencies with npm
        run: npm i
      - name: Run tests with npm
        run: npm run test
      - name: Build with npm
        run: npm run build
      - name: Build docs with npm
        run: npm run docs
      - name: Publish to npm
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          publish_command: "npm"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish docs to GitHub pages
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
          git-config-name: bot
          git-config-email: bot@example.com
          single-commit: true
